deploy:
  stage: deploy
  image: snowflake/snowflake-cli:latest
  before_script:
    - export SNOWSQL_PWD=$SNOWSQL_PWD
    - snowflake config set accountname $SNOWSQL_ACCOUNT
    - snowflake config set username $SNOWSQL_USER
    - snowflake config set password $SNOWSQL_PWD
    - snowflake config set region $SNOWSQL_ACCOUNT.region

  script:
    - snowflake streamlit deploy --name $STREAMLIT_APP_NAME --file app.py \
      --database $SNOWSQL_DATABASE --schema $SNOWSQL_SCHEMA --role $SNOWSQL_ROLE \
      --warehouse $SNOWSQL_WAREHOUSE

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'  # Only run if the branch is main
