name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SnowSQL
        run: |
          # Download the SnowSQL installer
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2.28/snowsql-linux_x86_64
          # Make it executable
          chmod +x snowsql-linux_x86_64
          # Move to /usr/local/bin and rename to snowflake
          sudo mv snowsql-linux_x86_64 /usr/local/bin/snowflake

      - name: Set up SnowSQL
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
          SNOWSQL_DATABASE: ${{ secrets.SNOWSQL_DATABASE }}
          SNOWSQL_SCHEMA: ${{ secrets.SNOWSQL_SCHEMA }}
          SNOWSQL_ROLE: ${{ secrets.SNOWSQL_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWSQL_WAREHOUSE }}
          STREAMLIT_APP_NAME: "my_streamlit_app"  # Customize this name
        run: |
          echo "Setting up SnowSQL..."
          mkdir -p ~/.snowsql  # Create the directory if it doesn't exist
          echo "[connections]" >> ~/.snowsql/config
          echo "accountname = ${SNOWSQL_ACCOUNT}" >> ~/.snowsql/config
          echo "username = ${SNOWSQL_USER}" >> ~/.snowsql/config
          echo "password = ${SNOWSQL_PWD}" >> ~/.snowsql/config
          echo "region = ${SNOWSQL_ACCOUNT#*.}" >> ~/.snowsql/config  # Adjust based on your account format

      - name: Deploy Streamlit App
        run: |
          snowflake streamlit deploy --name $STREAMLIT_APP_NAME --file app.py \
            --database $SNOWSQL_DATABASE --schema $SNOWSQL_SCHEMA --role $SNOWSQL_ROLE \
            --warehouse $SNOWSQL_WAREHOUSE
