stages:
  - deploy

variables:
  SNOWSQL_ACCOUNT: $SNOWSQL_ACCOUNT
  SNOWSQL_USER: $SNOWSQL_USER
  SNOWSQL_PWD: $SNOWSQL_PWD
  SNOWSQL_DATABASE: $SNOWSQL_DATABASE
  SNOWSQL_SCHEMA: $SNOWSQL_SCHEMA
  SNOWSQL_ROLE: $SNOWSQL_ROLE
  SNOWSQL_WAREHOUSE: $SNOWSQL_WAREHOUSE
  STREAMLIT_APP_NAME: "my_streamlit_app"  # Customize this name

deploy:
  stage: deploy
  image: snowflake/snowflake-cli:latest
  before_script:
    - export SNOWSQL_PWD=$SNOWSQL_PWD
    - snowflake config set accountname $SNOWSQL_ACCOUNT
    - snowflake config set username $SNOWSQL_USER
    - snowflake config set password $SNOWSQL_PWD
    - snowflake config set region $SNOWSQL_ACCOUNT.region
  script:
    - snowflake streamlit deploy --name $STREAMLIT_APP_NAME --file app.py \
      --database $SNOWSQL_DATABASE --schema $SNOWSQL_SCHEMA --role $SNOWSQL_ROLE \
      --warehouse $SNOWSQL_WAREHOUSE
  rules:
    - when: on_success  # This means the job will run on successful previous stages
