name: Deploy via Snowflake CLI

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Install Snowflake CLI'
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-cli==3.0.2


      # Add this step to ensure we're in the right directory
      - name: Change Directory to Root
        run: cd $GITHUB_WORKSPACE

      - name: 'Deploy the Streamlit app'
        shell: bash
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          ROLE: 'STREAMLIT_APP_DEVELOPER'
        run: |
         mkdir -p ~/.snowflake
         touch ~/.snowflake/config.toml
         echo "[CICD]" >> ~/.snowflake/config.toml   
         echo "account = \"$SNOWFLAKE_ACCOUNT\"" >> ~/.snowflake/config.toml
         echo "user = \"$SNOWFLAKE_USER\"" >> ~/.snowflake/config.toml
         echo "password = \"$SNOWFLAKE_PASSWORD\"" >> ~/.snowflake/config.toml   
         chmod 0600 ~/.snowflake/config.toml
         snow --config-file="~/.snowflake/config.toml" connection CICD
         snow streamlit deploy --replace --connection CICD
