name: Deploy via Snowflake CLI

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: '3.8'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Install Snowflake CLI'
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-cli-labs

      - name: 'Create config from secrets'
        env:
          SNOWCLI_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWCLI_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWCLI_PW: ${{ secrets.SNOWSQL_PW }}
          SNOWCLI_ROLE: ${{ secrets.SNOWSQL_ROLE }}
          SNOWCLI_DATABASE: ${{ secrets.SNOWSQL_DATABASE }}
          SNOWCLI_SCHEMA: ${{ secrets.SNOWSQL_SCHEMA }}
          SNOWCLI_WAREHOUSE: ${{ secrets.SNOWSQL_WAREHOUSE }}
        run: |
          mkdir -p ~/.snowflake
          cat << EOF > ~/.snowflake/config.toml
          [connections]
          account = "$SNOWCLI_ACCOUNT"
          user = "$SNOWCLI_USER"
          password = "$SNOWCLI_PW"
          role = "$SNOWCLI_ROLE"
          database = "$SNOWCLI_DATABASE"
          schema = "$SNOWCLI_SCHEMA"
          warehouse = "$SNOWCLI_WAREHOUSE"
          EOF
          chmod 0600 ~/.snowflake/config.toml

      - name: List files in the working directory
        run: ls -alh  # Check if snowflake.yml and app.py are here

      - name: 'Deploy the Streamlit app'
        run: snow streamlit deploy --replace
