name: Deploy via Snowflake CLI

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Install Snowflake CLI'
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-cli==3.0.2


      # Add this step to ensure we're in the right directory
      - name: Change Directory to Root
        run: cd $GITHUB_WORKSPACE

      - name: 'Deploy the Streamlit app'
        shell: bash
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          ROLE: 'STREAMLIT_APP_DEVELOPER'
        run: |
          snow connection add --connection-name cicd --account $SNOWFLAKE_ACCOUNT --username $SNOWFLAKE_USER --password $SNOWFLAKE_PASSWORD --warehouse '' --role '' --database '' --schema '' --host '' --port 0 --region '' --authenticator '' 
          snow streamlit deploy --replace --connection cicd
