name: Deploy via Snowflake CLI

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

env:
  PYTHON_VERSION: '3.10'
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_AUTHENTICATOR: SNOWFLAKE_JWT
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW }}
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_ROLE: 'streamlit_app_developer'
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_WAREHOUSE: "STREAMLIT_TEST_WH"
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE: "STREAMLIT_DB"
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_SCHEMA: "STREAMLIT_SC"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

     # Step 3: Install Snowflake CLI manually (run your custom script)
      - name: Install Snowflake CLI
        shell: bash
        run: |
          ls
          cd scripts
          ls
          bash install-snowcli.sh
        env:
          CLI_VERSION: "latest"  # Replace with a specific version if necessary

      # Step 4: Set up config.toml (run your custom config script)
      - name: Set up Snowflake CLI config file
        shell: bash
        run: |
          cd scripts
          bash setup-config-file.sh
        env:
          CONFIG_FILE_PATH: $GITHUB_WORKSPACE/config.toml 


      # Add this step to ensure we're in the right directory
      - name: Change Directory to Root
        run: cd $GITHUB_WORKSPACE

     # Use the CLI
      - name: Execute Snowflake CLI command
        run: |
          snow --version
          snow connection test
          
      - name: 'Deploy the Streamlit app'
        shell: bash
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          ROLE: 'STREAMLIT_APP_DEVELOPER'
        run: |
         snow streamlit deploy --replace --connection myconnection
         
